version: "3.7"
services:
  registry:
    image: registry:0.1
    labels: 
      MY_DLO_ENVIRONMENT: platform
      MY_DLO_PURPOSE: registry voor development images
    ports:
      # platform:56000+, dev:57000+, demo:58000+, pilot:59000+
      - 56001:5000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - platform-net
    secrets:
      - registry_htpasswd
      - registry_cert
      - registry_cert_key
    environment:
      REGISTRY_HTTP_SECRET: AVERYSECRETSECRET
      REGISTRY_HTTP_TLS_CERTIFICATE: /run/secrets/registry_cert
      REGISTRY_HTTP_TLS_KEY: /run/secrets/registry_cert_key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /run/secrets/registry_htpasswd
    volumes:
      - /var/registry:/var/lib/registry

networks:
  platform-net:
    external: true

secrets:
  registry_htpasswd:
    external: true
  registry_cert:
    external: true
  registry_cert_key:
    external: true
